# Generated by Django 3.2.6 on 2021-08-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_userprofile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='vaccinated',
        ),
    ]
