# Generated by Django 3.2.6 on 2021-08-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210830_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secret_key',
            field=models.CharField(default='', max_length=15),
        ),
    ]
